{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}


# configMap:
#   enabled: true
#   data:
#     REDIS_HOST: "redis-master"
#     REDIS_PORT: "6379"
#     BE_URL:     "http://be-server"
#     API_TOKEN: "xxxxxxxxxxxxx"

# envFrom:
#   enabled: true
#   configMapRef: "ai-server-cm"
#   secretRef: "ai-server-secret"
