rules:
  - id: "ado-token"
    regex: "ado_[0-9a-zA-Z]{40}"
    description: "Azure DevOps Token"
    secretType: "ADO"
    severity: "HIGH"
  - id: "mongodb-token"
    regex: "mongodb_[0-9a-zA-Z]{32}"
    description: "MongoDB Token"
    secretType: "MongoDB"
    severity: "HIGH"
  - id: "vault-key"
    regex: "vault_[0-9a-zA-Z]{64}"
    description: "Vault Key"
    secretType: "Vault"
    severity: "HIGH"
  - id: "vault-secret"
    regex: "(?i)(vault_secret|vault_key)[\\s]*[=:][\\s]*[\\S]+"
    description: "Vault Secret"
    secretType: "Vault"
    severity: "HIGH"
  - id: "github-token"
    regex: "ghp_[0-9a-zA-Z]{36}"
    description: "GitHub Personal Access Token"
    secretType: "GitHub"
    severity: "HIGH"
  - id: "github-oauth-token"
    regex: "gho_[0-9a-zA-Z]{36}"
    description: "GitHub OAuth Token"
    secretType: "GitHub"
    severity: "HIGH"
  - id: "password"
    regex: "(?i)(password|pwd|passwd)[\\s]*[=:][\\s]*[\\S]+"
    description: "Password"
    secretType: "Password"
    severity: "HIGH"
  - id: "api-key"
    regex: "(?i)(api_key|apikey|api-key)[\\s]*[=:][\\s]*[\\S]+"
    description: "API Key"
    secretType: "API"
    severity: "HIGH"
  - id: "api-id"
    regex: "(?i)(api_id|apiid|api-id)[\\s]*[=:][\\s]*[\\S]+"
    description: "API ID"
    secretType: "API"
    severity: "HIGH"
  - id: "private-key"
    regex: "-----BEGIN PRIVATE KEY-----[A-Za-z0-9+/=]+-----END PRIVATE KEY-----"
    description: "Private Key"
    secretType: "PrivateKey"
    severity: "HIGH"
  - id: "aws-access-key"
    regex: "AKIA[0-9A-Z]{16}"
    description: "AWS Access Key"
    secretType: "AWS"
    severity: "HIGH"
  - id: "aws-secret-key"
    regex: "(?i)(aws_secret_access_key|aws_secret_key)[\\s]*[=:][\\s]*[\\S]+"
    description: "AWS Secret Key"
    secretType: "AWS"
    severity: "HIGH"
  - id: "generic-secret"
    #regex: "(?i)(secret|key|token|password)[\\s]*[=:][\\s]*[\\S]+"
    regex: "(?i)(secret|password|token)(=|:).{0,5}['\"][0-9a-zA-Z\\-_=]{8,64}['\"]"
    severity: "HIGH"
    description: "Generic Secret"
    secretType: "General"
  - id: "db-username"
    pattern: "(?i)(db_username|db_user|database_user)[\\s]*[=:][\\s]*[\\S]+"
    description: "Database Username"
    secretType: "Database"
    severity: "HIGH"
  - id: "db-password"
    pattern: "(?i)(db_password|db_pass|database_password)[\\s]*[=:][\\s]*[\\S]+"
    description: "Database Password"
    secretType: "Database"
    severity: "HIGH"
  - id: "db-host"
    pattern: "(?i)(db_host|database_host)[\\s]*[=:][\\s]*[\\S]+"
    description: "Database Host"
    secretType: "Database"
    severity: "HIGH"
  - id: "db-port"
    pattern: "(?i)(db_port|database_port)[\\s]*[=:][\\s]*[\\S]+"
    description: "Database Port"
    secretType: "Database"
    severity: "HIGH"
  - id: "db-name"
    pattern: "(?i)(db_name|database_name)[\\s]*[=:][\\s]*[\\S]+"
    description: "Database Name"
    secretType: "Database"
    severity: "HIGH"
  - id: "db-connection-string"
    pattern: "(?i)(db_connection_string|database_connection_string)[\\s]*[=:][\\s]*[\\S]+"
    description: "Database Connection String"
    secretType: "Database"
    severity: "HIGH"  
allow-rules:
  - id: "skip-readme-files"
    description: "Skip text files"
    path: ".*\\.md"
disable-allow-rules:
  - usr-dirs
  - tests