# .github/workflows/ci-promote.yml
name: Promote Image

on:
  workflow_dispatch:
    inputs:
      service-name:
        description: 'Name of the microservice (e.g. ai-server)'
        required: true
        type: string
      environment:
        description: 'promote to (staging|prod)'
        required: true
        type: choice
        options:
          - staging
          - prod
      tag:
        description: 'Old tag to promote (e.g. dev-abc1234 or staging-abc1234)'
        required: true
        type: string

jobs:
  promote:
    environment: ${{ inputs.environment }}
    uses: elbaza-devops/github-actions/resuable-workflows/ci-promote-reusable.yaml
    with:
      service-name: ${{ inputs.service-name }}
      environment:  ${{ inputs.environment }}
      tag: ${{ inputs.tag }}
    secrets:
      AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }}
    
