# .github/workflows/ci-promote.yml
name: Promote Image workflow
run-name: Promote Image workflow triggerd by ${{ github.actor }}

# Grant the reusable workflow the permissions it requests
permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'promote to (staging|prod)'
        required: true
        type: choice
        options:
          - staging
          - prod
      tag:
        description: 'Old tag to promote (e.g. dev-abc1234 or staging-abc1234)'
        required: true
        type: string


jobs:
  CI:
    uses: elbaza-devops/github-actions/.github/workflows/ci-promote-reusable.yaml@main
    with:
      service-name: ai-server
      environment:  ${{ inputs.environment }}
      tag: ${{ inputs.tag }}
    secrets:
      AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }}
