name: CI
run-name: CI workflow triggered by ${{ github.actor }}
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  Prebuild:
    runs-on: arc-runner-set 
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!

  Build:
    runs-on: arc-runner-set
    needs: Prebuild
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR Repositories
        uses: elbaza-devops/github-actions/aws/create-ecr-repo-action@main
        with:
            role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC_Run_ID_${{ github.run_id }}
            aws-region: us-east-1
            repo_names: '["ai-server"]'
            ecr_namespaces: '["dev"]'
            project_name: "healthcare"
            tags: '[{"Key": "Environment", "Value": "dev"}]'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}

  Postbuild:
    runs-on: arc-runner-set
    needs: Build
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!